version: 2.1
jobs:
  build:
    docker:
      - image: docker:24.0.2-git
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apk add --update python3

      - run:
          name: Setup VirtualEnv
          command: |
            export TAG=0.1.${CIRCLE_BUILD_NUM}
            export IMAGE_NAME=echo-flask'

            python -m venv echo-flask
            . echo-flask/bin/activate

            pip install --no-cache-dir -r requirements.txt

      - run:
          name: Run Tests
          command: |
            . echo-flask/bin/activate

            echo "Running tests"
            env

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            . echo-flask/bin/activate

            cat $BASH_ENV

            docker build -t rhrlima/$IMAGE_NAME:$TAG .

            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin

            docker push rhrlima/$IMAGE_NAME:$TAG

      - run:
          name: Deploy App
          command: |
            echo "Deplying app (not really)"
