version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.10.9
    steps:
      - checkout

      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 

            virtualenv echo-flask
            . helloworld/bin/activate

            pip install --no-cache-dir -r requirements.txt

      - run:
          name: Run Tests
          command: |
            . helloworld/bin/activate

            echo "Running tests"
            env

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            . helloworld/bin/activate

            docker build -t rhrlima/$IMAGE_NAME:$TAG .

            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin

            docker push rhrlima/$IMAGE_NAME:$TAG

      - run:
          name: Deploy App
          command: |
            echo "Deplying app (not really)"
